"""
Interactive 2D Lennard-Jones MD applet for teaching.

Inspired by Daniel V. Schroeder's Interactive Molecular Dynamics web app
(hard walls, LJ 12-6, speed-coloured disks, phase presets). This Jupyter
widget version is a reimplementation for the MSSE summer school — not a
port of Schroeder's HTML/JS code.

Citation:
  D. V. Schroeder, "Interactive molecular dynamics,"
  Am. J. Phys. 83, 210–218 (2015). https://doi.org/10.1119/1.4901185
  App: https://physics.weber.edu/schroeder/md/InteractiveMD.html

Physics closely follows Schroeder's teaching design:
  - hard walls (spring force), not periodic boundaries
  - LJ 12-6 truncated at ~3σ
  - velocity Verlet
  - natural units (σ = ε = m = kB = 1)

Students only use widgets; they do not edit this file.
"""

from __future__ import annotations

import io
from dataclasses import dataclass, field

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
import ipywidgets as widgets


WALL_K = 50.0  # Schroeder wall spring constant
FORCE_CUTOFF = 3.0


@dataclass
class LJState:
    pos: np.ndarray
    vel: np.ndarray
    box: float  # square box side length L
    n: int
    epsilon: float = 1.0
    sigma: float = 1.0
    cutoff: float = FORCE_CUTOFF
    dt: float = 0.02
    temperature: float = 0.8
    step: int = 0
    pe: float = 0.0
    ke: float = 0.0
    pressure: float = 0.0
    history_t: list = field(default_factory=list)
    history_temp: list = field(default_factory=list)
    history_press: list = field(default_factory=list)


def _thermal_velocities(n: int, kinetic_temp: float, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    vel = rng.normal(size=(n, 2))
    vel -= vel.mean(axis=0)
    ke = 0.5 * np.sum(vel**2)
    target = n * kinetic_temp
    if ke > 0:
        vel *= np.sqrt(target / ke)
    return vel


def _pack_in_rect(
    n: int,
    x0: float,
    x1: float,
    y0: float,
    y1: float,
    min_dist: float,
    seed: int,
    *,
    disordered: bool = False,
    fill: bool = False,
) -> np.ndarray:
    """Place n points in a rectangle with approximate minimum separation.

    disordered=True: jitter so the fluid looks liquid, not crystalline.
    fill=True: spread across the *whole* rectangle (gases). Without fill,
    a fixed cell packs from the bottom-left and can look like a strip.
    """
    rng = np.random.default_rng(seed)
    width = max(x1 - x0, 1e-6)
    height = max(y1 - y0, 1e-6)

    if fill:
        # Even lattice spanning the full box (dilute gases).
        aspect = width / height
        ncols = max(1, int(np.ceil(np.sqrt(n * aspect))))
        nrows = max(1, int(np.ceil(n / ncols)))
        while ncols * nrows < n:
            if width / (ncols + 1) >= height / (nrows + 1):
                ncols += 1
            else:
                nrows += 1
        dx = width / ncols
        dy = height / nrows
        pos = np.zeros((n, 2))
        k = 0
        for row in range(nrows):
            for col in range(ncols):
                if k >= n:
                    break
                x = x0 + (col + 0.5) * dx + 0.18 * dx * rng.normal()
                y = y0 + (row + 0.5) * dy + 0.18 * dy * rng.normal()
                pos[k] = (x, y)
                k += 1
            if k >= n:
                break
        pos[:, 0] = np.clip(pos[:, 0], x0, x1)
        pos[:, 1] = np.clip(pos[:, 1], y0, y1)
        return pos

    cell = max(min_dist, 1.05)
    ncols = max(1, int(np.floor(width / cell)))
    nrows = max(1, int(np.ceil(n / ncols)))
    while ncols * nrows < n:
        cell *= 0.98
        ncols = max(1, int(np.floor(width / cell)))
        nrows = max(1, int(np.ceil(n / ncols)))

    pos = np.zeros((n, 2))
    k = 0
    for row in range(nrows):
        for col in range(ncols):
            if k >= n:
                break
            x = x0 + (col + 0.5) * cell
            y = y0 + (row + 0.5) * cell
            if disordered:
                if row % 2:
                    x += 0.5 * cell
                x += 0.28 * cell * rng.normal()
                y += 0.28 * cell * rng.normal()
            else:
                x += 0.02 * rng.normal()
                y += 0.02 * rng.normal()
            pos[k] = (x, y)
            k += 1
        if k >= n:
            break

    pos[:, 0] = np.clip(pos[:, 0], x0, x1)
    pos[:, 1] = np.clip(pos[:, 1], y0, y1)

    if disordered:
        cut2 = (min_dist * 0.90) ** 2
        for _ in range(6):
            moved = False
            for i in range(n - 1):
                d = pos[i + 1 :] - pos[i]
                r2 = np.sum(d * d, axis=1)
                hit = r2 < cut2
                if not np.any(hit):
                    continue
                moved = True
                r = np.sqrt(np.maximum(r2[hit], 1e-12))
                push = d[hit] / r[:, None] * 0.5 * (min_dist * 0.90 - r)[:, None]
                pos[i] -= push.sum(axis=0)
                pos[i + 1 :][hit] += push
            pos[:, 0] = np.clip(pos[:, 0], x0, x1)
            pos[:, 1] = np.clip(pos[:, 1], y0, y1)
            if not moved:
                break
    return pos


def _pack_random(
    n: int,
    box: float,
    margin: float,
    seed: int,
    *,
    disordered: bool = False,
    fill: bool = False,
    min_dist: float = 1.05,
) -> np.ndarray:
    """Place n non-overlapping disks (approx) inside the box."""
    return _pack_in_rect(
        n, margin, box - margin, margin, box - margin,
        min_dist=min_dist, seed=seed, disordered=disordered, fill=fill,
    )


def _hex_crystal(n: int, a: float = 1.10) -> tuple[np.ndarray, float]:
    """Compact hexagonal crystallite; returns positions (centred later) and span."""
    ncols = int(np.ceil(np.sqrt(n)))
    nrows = int(np.ceil(n / ncols))
    while ncols * nrows < n:
        nrows += 1
    pos = _hex_block(nrows, ncols, a)[:n]
    span = max(pos[:, 0].max() - pos[:, 0].min(), pos[:, 1].max() - pos[:, 1].min()) + a
    return pos, span


def _hex_block(nrows: int, ncols: int, a: float = 1.10) -> np.ndarray:
    """Rectangular hexagonal lattice block (nrows × ncols)."""
    pos = []
    for row in range(nrows):
        for col in range(ncols):
            x = (col + 0.5) * a + (0.5 * a if row % 2 else 0.0)
            y = (row + 0.5) * (a * np.sqrt(3) / 2.0)
            pos.append([x, y])
    return np.asarray(pos, float)


def _forces(state: LJState) -> tuple[np.ndarray, float, float]:
    """LJ + wall springs (Schroeder). Returns accel, PE, wall pressure contrib."""
    pos = state.pos
    n = state.n
    L = state.box
    eps, sig, rc = state.epsilon, state.sigma, state.cutoff
    ax = np.zeros_like(pos)
    pe = 0.0
    wall_force = 0.0
    rc2 = rc * rc
    sig2 = sig * sig
    inv_rc2 = 1.0 / rc2
    inv_rc6 = inv_rc2**3
    e_shift = 4.0 * eps * (inv_rc2**6 - inv_rc6)

    # walls
    for i in range(n):
        x, y = pos[i]
        if x < 0.5:
            fx = WALL_K * (0.5 - x)
            ax[i, 0] += fx
            wall_force += fx
            pe += 0.5 * WALL_K * (0.5 - x) ** 2
        elif x > L - 0.5:
            fx = WALL_K * (L - 0.5 - x)
            ax[i, 0] += fx
            wall_force -= fx
            pe += 0.5 * WALL_K * (L - 0.5 - x) ** 2
        if y < 0.5:
            fy = WALL_K * (0.5 - y)
            ax[i, 1] += fy
            wall_force += fy
            pe += 0.5 * WALL_K * (0.5 - y) ** 2
        elif y > L - 0.5:
            fy = WALL_K * (L - 0.5 - y)
            ax[i, 1] += fy
            wall_force -= fy
            pe += 0.5 * WALL_K * (L - 0.5 - y) ** 2

    # LJ pairs
    for i in range(n - 1):
        rij = pos[i + 1 :] - pos[i]
        r2 = np.sum(rij * rij, axis=1)
        mask = (r2 < rc2) & (r2 > 1e-12)
        if not np.any(mask):
            continue
        r2m = r2[mask]
        rijm = rij[mask]
        inv_r2 = 1.0 / r2m
        sr2 = sig2 * inv_r2
        sr6 = sr2**3
        sr12 = sr6**2
        pe += np.sum(4.0 * eps * (sr12 - sr6) - e_shift)
        ff = 24.0 * eps * inv_r2 * (2.0 * sr12 - sr6)
        fi = ff[:, None] * rijm
        ax[i] -= fi.sum(axis=0)
        ax[i + 1 :][mask] += fi

    pressure = wall_force / (4.0 * L)  # Schroeder instantaneous wall pressure
    return ax, pe, pressure


def _thermostat(vel: np.ndarray, temperature: float, n: int) -> np.ndarray:
    ke = 0.5 * np.sum(vel**2)
    target = n * temperature
    if ke > 1e-16:
        vel = vel * np.sqrt(target / ke)
    return vel


def step_md(state: LJState, thermostat_every: int = 40) -> None:
    a, pe, pressure = _forces(state)
    state.pos = state.pos + state.vel * state.dt + 0.5 * a * state.dt**2
    a2, pe, pressure = _forces(state)
    state.vel = state.vel + 0.5 * (a + a2) * state.dt
    state.step += 1
    if state.step % thermostat_every == 0:
        state.vel = _thermostat(state.vel, state.temperature, state.n)
    state.pe = pe
    state.ke = 0.5 * np.sum(state.vel**2)
    state.pressure = pressure
    if state.step % 5 == 0:
        _record_thermo(state)


def _record_thermo(state: LJState, force: bool = False) -> None:
    temp = state.ke / max(state.n, 1)
    if force or state.step % 5 == 0 or state.step <= 1:
        state.history_t.append(state.step * state.dt)
        state.history_temp.append(temp)
        state.history_press.append(state.pressure)
        if len(state.history_t) > 400:
            state.history_t = state.history_t[-400:]
            state.history_temp = state.history_temp[-400:]
            state.history_press = state.history_press[-400:]


def compute_rdf(pos: np.ndarray, box: float, nbins: int = 50, rmax: float | None = None) -> tuple[np.ndarray, np.ndarray]:
    """g(r) in a square box with walls (no PBC). Pair histogram / 2D ideal gas."""
    n = len(pos)
    if rmax is None:
        rmax = min(0.45 * box, 5.0)
    edges = np.linspace(0.0, rmax, nbins + 1)
    hist = np.zeros(nbins)
    for i in range(n - 1):
        d = np.linalg.norm(pos[i + 1 :] - pos[i], axis=1)
        hist += np.histogram(d, bins=edges)[0]
    dens = n / (box * box)
    r = 0.5 * (edges[:-1] + edges[1:])
    dr = edges[1] - edges[0]
    # hist counts each pair once; ideal count in shell ≈ (N * dens * 2π r dr) / 2
    shell_area = 2.0 * np.pi * r * dr
    denom = 0.5 * n * dens * shell_area
    g = np.zeros_like(hist)
    mask = denom > 1e-12
    g[mask] = hist[mask] / denom[mask]
    return r, g


def density_profile_x(pos: np.ndarray, box: float, nbins: int = 40) -> tuple[np.ndarray, np.ndarray]:
    hist, edges = np.histogram(pos[:, 0], bins=nbins, range=(0.0, box))
    centers = 0.5 * (edges[:-1] + edges[1:])
    area = (edges[1] - edges[0]) * box
    return centers, hist / area


def make_state(preset: str = "liquid", seed: int = 1) -> LJState:
    """
    Schroeder Fig. 2–style presets (scaled particle numbers for Jupyter speed).
    Densities chosen so phases are visually obvious with hard walls.
    """
    if preset == "gas":
        # dilute, scattered over the *whole* box (not a bottom strip)
        n, L, T = 50, 26.0, 1.20
        pos = _pack_random(n, L, margin=1.2, seed=seed, fill=True)
    elif preset == "liquid":
        # dense disordered fluid filling the box (not a grid — grids look solid)
        n, L, T = 100, 12.0, 0.70
        pos = _pack_random(n, L, margin=0.7, seed=seed, disordered=True)
    elif preset == "solid":
        # hexagonal crystal packing the box
        n, T = 100, 0.20
        crystal, span = _hex_crystal(n, a=1.10)
        L = span + 0.4
        pos = crystal - crystal.min(axis=0) + 0.7
        # fit L to crystal
        L = float(max(pos[:, 0].max(), pos[:, 1].max()) + 0.7)
    elif preset == "liquid_gas":
        # Compact *disordered* droplet + empty vapour (not a crystal clump)
        n, L, T = 90, 22.0, 0.45
        rng = np.random.default_rng(seed)
        drop = _hex_crystal(n, a=1.14)[0]
        drop = drop - drop.mean(axis=0) + L / 2.0
        drop += 0.12 * rng.normal(size=drop.shape)
        # Soft push so melt jitter does not create overlaps
        cut2 = 0.95**2
        for _ in range(8):
            moved = False
            for i in range(n - 1):
                d = drop[i + 1 :] - drop[i]
                r2 = np.sum(d * d, axis=1)
                hit = r2 < cut2
                if not np.any(hit):
                    continue
                moved = True
                r = np.sqrt(np.maximum(r2[hit], 1e-12))
                push = d[hit] / r[:, None] * 0.5 * (0.95 - r)[:, None]
                drop[i] -= push.sum(axis=0)
                drop[i + 1 :][hit] += push
            if not moved:
                break
        pos = drop
    elif preset == "solid_gas":
        # Sharp hex crystal clump + vapour (keep lattice obvious)
        n, L, T = 100, 22.0, 0.25
        crystal, _ = _hex_crystal(n, a=1.10)
        c = crystal.mean(axis=0)
        pos = crystal - c + L / 2.0
    elif preset == "solid_liquid":
        # Dense hex crystal (left) + disordered, lower-density fluid (right).
        # Visually opposite of liquid_gas (slab interface, not a centred droplet).
        nrows, ncols = 12, 5
        n_s = nrows * ncols
        n_l = 40
        n = n_s + n_l
        a_s = 1.08
        gap = 1.25
        margin = 0.80
        T = 0.32

        cryst = _hex_block(nrows, ncols, a_s)
        cryst = cryst - cryst.min(axis=0)
        height = float(cryst[:, 1].max())
        solid_w = float(cryst[:, 0].max())
        liq_w = 7.5
        L = float(max(height, solid_w + gap + liq_w) + 2.0 * margin)
        y0 = 0.5 * (L - height)

        cryst[:, 0] += margin
        cryst[:, 1] += y0

        x_left = float(cryst[:, 0].max() + gap)
        liq = _pack_in_rect(
            n_l,
            x0=x_left,
            x1=L - margin,
            y0=margin,
            y1=L - margin,
            min_dist=1.12,
            seed=seed + 5,
            disordered=True,
        )

        pos = np.vstack([cryst, liq])
        pos[:, 0] = np.clip(pos[:, 0], 0.65, L - 0.65)
        pos[:, 1] = np.clip(pos[:, 1], 0.65, L - 0.65)
    else:
        n, L, T = 80, 16.0, 0.70
        pos = _pack_random(n, L, margin=0.8, seed=seed, disordered=True)

    if preset != "solid_liquid":
        pos = np.clip(pos, 0.55, L - 0.55)
    vel = _thermal_velocities(n, T, seed + 7)
    return LJState(pos=pos, vel=vel, box=float(L), n=n, dt=0.02, temperature=T)


def show_applet():
    """Launch Schroeder-style teaching applet (widgets only)."""
    import asyncio

    state = {
        "s": make_state("liquid_gas"),
        "log": [],
        "ready": False,
        "running": False,
        "frame": 0,
    }

    preset = widgets.Dropdown(
        options=[
            ("Gas", "gas"),
            ("Liquid", "liquid"),
            ("Solid", "solid"),
            ("Liquid + gas", "liquid_gas"),
            ("Solid + gas", "solid_gas"),
            ("Solid + liquid", "solid_liquid"),
        ],
        value="liquid_gas",
        description="Preset",
        layout=widgets.Layout(width="320px"),
    )
    T = widgets.FloatSlider(value=0.45, min=0.15, max=1.5, step=0.05, description="T*", continuous_update=False)
    dt = widgets.FloatSlider(
        value=0.020, min=0.001, max=0.12, step=0.005, description="Δt",
        readout_format=".3f", continuous_update=False,
    )
    steps_per_frame = widgets.IntSlider(value=20, min=5, max=80, step=5, description="Steps/frame")

    # Toggle + asyncio loop: widgets.Play only fires once when redraw is slow.
    btn_play = widgets.ToggleButton(
        value=False,
        description="Play ▶",
        button_style="success",
        tooltip="Run continuously",
        layout=widgets.Layout(width="100px"),
    )
    btn_reset = widgets.Button(description="Reset", button_style="warning")
    btn_step = widgets.Button(description="Step once", button_style="info")
    btn_record = widgets.Button(description="Record T, P, ρ, g(r)", button_style="primary")
    status = widgets.HTML(value="")
    log_html = widgets.HTML(value="<b>Recorded notes</b><br><i>none yet</i>")
    image = widgets.Image(format="png")

    fig, axes = plt.subplots(1, 3, figsize=(12.5, 3.8))
    ax, ax2, ax3 = axes
    ax.set_aspect("equal")
    ax.set_title("Atoms")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    (line_t,) = ax2.plot([], [], color="#1f4e79", lw=1.5, label="T")
    ax2.set_ylabel("T", color="#1f4e79")
    ax2.tick_params(axis="y", labelcolor="#1f4e79")
    ax2b = ax2.twinx()
    (line_p,) = ax2b.plot([], [], color="#c45c26", lw=1.2, label="P")
    ax2b.set_ylabel("P", color="#c45c26")
    ax2b.tick_params(axis="y", labelcolor="#c45c26")
    ax2.set_title("Instantaneous T and P")
    ax2.set_xlabel("time")
    ax2.legend([line_t, line_p], ["T", "P"], loc="upper right", fontsize=8)
    (line_g,) = ax3.plot([], [], color="#2d6a4f", lw=1.6)
    ax3.axhline(1.0, ls="--", color="gray", lw=0.8)
    ax3.set_title("Radial distribution g(r)")
    ax3.set_xlabel("r")
    ax3.set_ylabel("g(r)")
    fig.tight_layout()
    plt.close(fig)

    PRESET_DEFAULTS = {
        "gas": {"T": 1.20, "dt": 0.020, "steps": 20},
        "liquid": {"T": 0.70, "dt": 0.015, "steps": 20},
        "solid": {"T": 0.20, "dt": 0.015, "steps": 20},
        "liquid_gas": {"T": 0.45, "dt": 0.015, "steps": 20},
        "solid_gas": {"T": 0.25, "dt": 0.015, "steps": 20},
        "solid_liquid": {"T": 0.32, "dt": 0.012, "steps": 15},
    }

    def _apply_defaults() -> None:
        d = PRESET_DEFAULTS[preset.value]
        T.value = d["T"]
        dt.value = d["dt"]
        steps_per_frame.value = d["steps"]

    def _sync(s: LJState) -> None:
        s.temperature = float(T.value)
        s.dt = float(dt.value)

    def _draw_atoms(s: LJState) -> None:
        ax.clear()
        ax.set_aspect("equal")
        ax.set_xlim(0, s.box)
        ax.set_ylim(0, s.box)
        ax.set_title("Atoms")
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.plot([0, s.box, s.box, 0, 0], [0, 0, s.box, s.box, 0], color="#333", lw=1.2)
        speeds = np.linalg.norm(s.vel, axis=1)
        # scatter is much faster than per-atom Circle patches
        ax.scatter(
            s.pos[:, 0],
            s.pos[:, 1],
            c=speeds,
            cmap="plasma",
            vmin=0.0,
            vmax=3.0,
            s=55,
            linewidths=0,
            alpha=0.95,
        )

    def draw(_=None, *, update_rdf: bool = True) -> None:
        s = state["s"]
        _draw_atoms(s)

        if s.history_t:
            line_t.set_data(s.history_t, s.history_temp)
            line_p.set_data(s.history_t, s.history_press)
            ax2.relim()
            ax2.autoscale_view()
            ax2b.relim()
            ax2b.autoscale_view()

        if update_rdf:
            r, g = compute_rdf(s.pos, s.box)
            line_g.set_data(r, g)
            ax3.relim()
            ax3.autoscale_view()
            ax3.set_ylim(bottom=0)

        buf = io.BytesIO()
        # bbox_inches='tight' is slow; fixed size is enough for the widget
        fig.savefig(buf, format="png", dpi=80)
        image.value = buf.getvalue()

        if "BLEW UP" in (status.value or ""):
            return
        temp = s.ke / max(s.n, 1)
        dens = s.n / (s.box * s.box)
        tip = {
            "gas": "Look for: sparse, fills box; g(r)≈1 after short peak.",
            "liquid": "Look for: dense, disordered; g(r) has 2–3 decaying shells.",
            "solid": "Look for: crystal lattice; g(r) has sharp lasting peaks.",
            "liquid_gas": "Look for: disordered droplet in the centre + vapour around it.",
            "solid_gas": "Look for: sharp crystal clump + vapour.",
            "solid_liquid": "Look for: hex crystal on the left; looser disordered fluid on the right.",
        }.get(preset.value, "")
        status.value = (
            f"<code>step={s.step}</code> &nbsp; N={s.n} &nbsp; L={s.box:.1f} &nbsp; "
            f"ρ≈{dens:.3f} &nbsp; T≈{temp:.3f} (set {s.temperature:.3f}) &nbsp; "
            f"P≈{s.pressure:.3f} &nbsp; Δt={s.dt}"
            f"<br><i>{tip}</i>"
        )

    def _advance(nsteps: int) -> bool:
        s = state["s"]
        _sync(s)
        for _ in range(nsteps):
            try:
                step_md(s)
            except Exception:
                _blow_up("numerical overflow")
                return False
            if (
                not np.isfinite(s.pos).all()
                or not np.isfinite(s.vel).all()
                or abs(s.pe) > 1e6
                or abs(s.ke) > 1e6
            ):
                _blow_up("energy exploded — Δt too large")
                return False
        _record_thermo(s, force=True)
        return True

    def _stop_play() -> None:
        state["running"] = False
        btn_play.value = False
        btn_play.description = "Play ▶"
        btn_play.button_style = "success"

    def _blow_up(reason: str) -> None:
        _stop_play()
        status.value = (
            f"<b style='color:#b00020'>SIMULATION BLEW UP</b> — {reason}. "
            "Lower <b>Δt</b> (try 0.01–0.02) and press <b>Reset</b>."
        )

    def reset(_=None) -> None:
        _stop_play()
        _apply_defaults()
        s = make_state(preset.value)
        s.temperature = float(T.value)
        s.dt = float(dt.value)
        s.ke = 0.5 * np.sum(s.vel**2)
        s.pressure = 0.0
        _record_thermo(s, force=True)
        state["s"] = s
        state["frame"] = 0
        status.value = ""
        draw(update_rdf=True)

    def step_once(_=None) -> None:
        _stop_play()
        _advance(int(steps_per_frame.value))
        draw(update_rdf=True)

    async def _run_loop() -> None:
        if state.get("loop_active"):
            return
        state["loop_active"] = True
        try:
            # Yield so the ToggleButton UI updates before the first heavy frame.
            await asyncio.sleep(0)
            while state["running"] and btn_play.value:
                ok = _advance(int(steps_per_frame.value))
                state["frame"] += 1
                # RDF is expensive — refresh every 3rd frame while running.
                draw(update_rdf=(state["frame"] % 3 == 0))
                if not ok:
                    _stop_play()
                    break
                await asyncio.sleep(0.02)
        finally:
            state["loop_active"] = False

    def on_play_toggle(change) -> None:
        if not state.get("ready") or change.get("name") != "value":
            return
        if change["new"]:
            state["running"] = True
            btn_play.description = "Pause ⏸"
            btn_play.button_style = "danger"
            try:
                asyncio.get_running_loop().create_task(_run_loop())
            except RuntimeError:
                asyncio.ensure_future(_run_loop())
        else:
            state["running"] = False
            btn_play.description = "Play ▶"
            btn_play.button_style = "success"

    def record(_=None) -> None:
        s = state["s"]
        temp = s.ke / max(s.n, 1)
        dens = s.n / (s.box * s.box)
        press = float(s.pressure)
        r, g = compute_rdf(s.pos, s.box)
        gmax = float(np.max(g)) if len(g) else 0.0
        state["log"].append(
            {
                "preset": preset.value,
                "T": temp,
                "P": press,
                "rho": dens,
                "gmax": gmax,
            }
        )
        rows = "<br>".join(
            f"<b>{e['preset']}</b>: T≈{e['T']:.3f}, P≈{e['P']:.3f}, "
            f"ρ≈{e['rho']:.3f}, max g(r)≈{e['gmax']:.2f}"
            for e in state["log"]
        )
        log_html.value = "<b>Recorded notes</b> (instantaneous)<br>" + rows

    btn_reset.on_click(reset)
    btn_step.on_click(step_once)
    btn_record.on_click(record)
    btn_play.observe(on_play_toggle, names="value")
    preset.observe(lambda c: reset() if c["name"] == "value" else None, names="value")

    controls = widgets.VBox(
        [
            widgets.HTML(
                "<h3>Lennard-Jones MD</h3>"
                "<p>Hard walls · atoms drawn as disks. "
                "<b>Colour = speed</b> (plasma scale: darker = slower, brighter/yellow = faster) "
                "— not element type. "
                "Choose a <b>Preset</b>, then <b>Reset</b>. "
                "Use <b>Play ▶</b> / Pause, or <b>Step once</b>. "
                "Status line and <b>Record</b> show T, P, and number density ρ = N/L². "
                "Right panel: <b>g(r)</b> — sharp lasting peaks = solid; "
                "decaying shells = liquid; nearly flat = gas.</p>"
                "<p style='font-size:0.9em;color:#555'>"
                "<b>Acknowledgement.</b> Design inspired by "
                "D.&nbsp;V.&nbsp;Schroeder’s "
                "<a href='https://physics.weber.edu/schroeder/md/InteractiveMD.html' target='_blank'>"
                "Interactive Molecular Dynamics</a> "
                "(Am.&nbsp;J.&nbsp;Phys. <b>83</b>, 210–218, 2015; "
                "<a href='https://doi.org/10.1119/1.4901185' target='_blank'>doi:10.1119/1.4901185</a>). "
                "This notebook applet is a teaching reimplementation, not a copy of that software."
                "</p>"
            ),
            widgets.HBox([preset, T, dt]),
            widgets.HBox([steps_per_frame, btn_reset, btn_play, btn_step, btn_record]),
            status,
            log_html,
            image,
        ]
    )
    display(controls)
    reset()
    state["ready"] = True
    return None
